FROM python:3.10-buster
EXPOSE 8000
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY . /code
#CMD ["hypercorn", "--bind", "localhost:9000",  "server:app"]
CMD ["hypercorn",  "server:app", "--bind", "0.0.0.0:8000"]
