version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - visimanagementapi_prod

networks:
  visimanagementapi_prod:
    driver: bridge
